#spring:
#  application:
#    name: microservice-discovery-eureka-ha
#
#server:
#  port: 8761
#eureka:
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 30000

#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}

server:
  port: 8761
eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:peer1} #服务主机名
    appname: ${spring.application.name} #服务名称，默认为 unknow 这里直接取 spring.application.name 了
  client:
    register-with-eureka: ${BOOL_REGISTER:true} # 是否把服务中心本身当做eureka client 注册。默认为true
    fetch-registry: ${BOOL_FETCH:true} # 是否拉取 eureka server 的注册信息。 默认为true
    service-url:
      defaultZone: ${EUREKA_URL_LIST:http://peer1:8761/eureka/} # 指定服务中心 eureka server的地址
  server:
    enable-self-preservation: ${SELF_PRESERVATION:true} # 是否开启自我保护。 默认为 true.
    eviction-interval-timer-in-ms: 30000

spring:
  application:
    name: ${EUREKA_APPLICATION_NAME:microservice-discovery-eureka-ha}


logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /tmp/logs/discovery-eureka.log
  level:
    root: INFO